name: DaisyLib
version: '${project.version} ${buildDescription}'
main: uk.firedev.daisylib.local.DaisyLib
api-version: '1.21'
author: FireML
description: ${project.description}
folia-supported: true
dependencies:
  server:
    Vault:
      required: true
      load: BEFORE
    Denizen:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE