name: DaisyLib
version: '${project.version} ${buildDescription}'
main: uk.firedev.daisylib.lib.DaisyLib
api-version: '1.20'
author: FireML
description: ${project.description}
commands:
  daisylib:
    description: "Manage the plugin"
    permission: "daisylib.command"
folia-supported: true
softdepend:
  - Denizen
  - PlaceholderAPI